### PR TITLE
Feature/test scope

### PR DESCRIPTION
**Pull request by bilyush**
Hi @gseitz ,
I would like to propose an extension to support Test/Compile scopes. I tried to write some tests with protobuf and sbt-protobuf

Please let me know what do you think? Can we merge it and make a release?

### CODE REVIEW

**Comment by gseitz** [comment]
Hi Boris,
Sorry for not getting back to you sooner.

How does this work now with depending on proto files in other jars? Now that the `protobuf` config is no more, how should these dependencies specified?

**Comment by gseitz** [comment]
Let me clarify: my worry is that in big projects, before each compilation sbt-protobuf would go and check each jar file for `.proto` files, which could be quite costly in terms of time.

**Comment by bilyush** [comment]
Hi Gerolf, thank you for the reply. 

I have tested that with the following case: I have the basic project (BP) and some particular implementation (Impl). BP contains .proto files, and Impl contains .proto files and ```import``` definitions, which links to the BP's files. 

Regarding to the performance - I'm not sure that I got it correct. The current implementation do not add additional compilation, if there is no .proto files in test. The previous one didn't allow to use .proto files in test. Could you please give me more details about it?

After we clarify all this questions I'll update this PR to the current state ```0.4.0```

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt-protobuf/pull/43

**Pull request closed without merging**
